export default class ActionType {
  static GET_ALL_CAMPUS = "GET_ALL_CAMPUS";
  static GET_ALL_CAMPUS_SUCCESS = "GET_ALL_CAMPUS_SUCCESS";
  static GET_ALL_CAMPUS_FAIL = "GET_ALL_CAMPUS_FAIL";

  static ADD_CAMPUS = "ADD_CAMPUS";
  static ADD_CAMPUS_SUCCESS = "ADD_CAMPUS_SUCCESS";
  static ADD_CAMPUS_FAIL = "ADD_CAMPUS_FAIL";

  static EDIT_CAMPUS = "EDIT_CAMPUS";
  static EDIT_CAMPUS_SUCCESS = "EDIT_CAMPUS_SUCCESS";
  static EDIT_CAMPUS_FAIL = "EDIT_CAMPUS_FAIL";

  static DELETE_CAMPUS = "DELETE_CAMPUS";
  static DELETE_CAMPUS_SUCCESS = "DELETE_CAMPUS_SUCCESS";
  static DELETE_CAMPUS_FAIL = "DELETE_CAMPUS_FAIL";

  static ADD_CAMPUS_STUDENT = "ADD_CAMPUS_STUDENT";
  static ADD_CAMPUS_STUDENT_SUCCESS = "ADD_CAMPUS_STUDENT_SUCCESS";
  static ADD_CAMPUS_STUDENT_FAIL = "ADD_CAMPUS_STUDENT_FAIL";

  static DELETE_CAMPUS_STUDENT = "DELETE_CAMPUS_STUDENT";
  static DELETE_CAMPUS_STUDENT_SUCCESS = "DELETE_CAMPUS_STUDENT_SUCCESS";
  static DELETE_CAMPUS_STUDENT_FAIL = "DELETE_CAMPUS_STUDENT_FAIL";
}
